### PR TITLE
Fix/http contact

### PR DESCRIPTION
**Pull request by wrathinmind**
## Description

ManX plugin has a problem in communication with manx agent: it awaits only for part of a second for the response. 
If the response calculation takes more time (e.g. find command) the result will be 
e.g sleep 5 && ls
[Errno 11] Resource temporarily unavailable

This happens because of improper await server usage (write and read are blocking), so I changed the socket with writer and reader.

For a while I've left a 10 second timeout.

Also, it is really strange that caldera (as a core, framework) uses Session object from a plugin ManX, so I moved Session class from ManX to http_contact ( because Session is never used anywhere else)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by wrathinmind** [comment]
Hi, could you please explain whet can be wrong with "Greetings / greeting (pull_request) — greeting" error? 
Can't figure it out "Error: Resource not accessible by integration"

**Comment by uruwhy** [comment]
I tried out the manx agent with the above fixes. Upon the agent's first beacon to the server, the following error occurs
```
2021-02-17 16:46:49 - DEBUG (contact_svc.py:64 handle_heartbeat) First time tcp beacon from rgscxb
2021-02-17 16:46:49 - ERROR (contact_tcp.py:83 send) Expecting value: line 2 column 1 (char 1)
Traceback (most recent call last):
  File "/Users/cualquierweon/webiando/tea_kettle/tea_kettle_base/app/contacts/contact_tcp.py", line 79, in send
    response = json.loads(response)
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
2021-02-17 16:46:49 - ERROR (contact_tcp.py:86 send) string indices must be integers
Traceback (most recent call last):
  File "/Users/cualquierweon/webiando/tea_kettle/tea_kettle_base/app/contacts/contact_tcp.py", line 84, in send
    return response['status'], response["pwd"], response['response']
TypeError: string indices must be integers
2021-02-17 16:46:59 - DEBUG (contact_svc.py:48 handle_heartbeat) Incoming tcp beacon from rgscxb
```

There's also an issue with command output not coming back until another command is passed to the agent (for instance, if I ask the agent to run `ls`, the ls output doesn't show up until the next command). Screenshot below:
Screen Shot 2021-02-17 at 16 49 17

**Review by wbooth — CHANGES_REQUESTED** [review]
Thanks for the submission, can you address some of the feedback from @uruwhy -- we're happy to help with any questions

**Comment by wbooth** [comment]
please feel free to re-open when the comments are addressed. We really appreciate you contributing!

**Pull request closed without merging**
