### PR TITLE
Draft: Alt Command Toggle

### PR DESCRIPTION
**Pull request by matthewRekos**
## Description

Alternative command feature in ability YAML which allows a user to flip a toggle when adding an operational link.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update
  - [ ] https://github.com/mitre/fieldmanual/pull/112 <-- PR for documentation in field manual 

## How Has This Been Tested?

Mostly manual tests - would need advisement on UI element testing

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by clenk — COMMENTED** [review]
What does the slider look like for abilities that don't have an alt_command? Ideally it doesn't appear.

I wonder if labels should go under `command` and `alt_command` instead of their own list. What happens if there's more than 2 labels? I assume any beyond the first 2 are ignored. What if there are no labels? What if there's only 1? Ideally we have default labels if they aren't present in the yaml.

**Comment by matthewRekos** [comment]
- If the labels aren't present then it defaults to Command1 and Command2 in the operations.html template. 
- If alt_command isn't given then the toggle doesn't appear. The UI element only appears if the alt_command is present.

Fixing the "1 label" use case now..

**Comment by matthewRekos** [comment]
app/objects/c_executor.py now has the default labels and if the label length is 1 it'll add a "Command2 default. If you have more than 2 its just uses the first 2.

**Comment by matthewRekos** [comment]
@clenk  any progress?

**Pull request closed without merging**
