### PR TITLE
Add paw to existing Fact only if Fact wasn't used in Link command

### PR DESCRIPTION
**Pull request by mchan143**
## Description

Follow up bug fix to https://github.com/mitre/caldera/pull/2397. This change proposes that paws are only added to a Fact's `collected_by` if they were not used in the command, which resolves the issue when relationships are created for seeded facts and seeded facts go through the `save_fact` process. Seeded facts should not be updated to show they have been collected by an agent if they were only used in the command.

The proposed change also resolves the scenario where an operation started with a seeded fact (say `domain.user.name`) and further discovery actions by an agent led to the re-discovery of the same fact. The paw will be added to a Fact's `collected_by` in this case.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Ran an operation against two agents that used seeded facts and learned facts. Ensured that the agent paws were not added to the seeded facts' `collected_by`.
- Added a test for the scenario mentioned above

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [N/A] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by ArtificialErmine — APPROVED** [review]
LGTM, nice use of the existing data structures to filter out what already has been processed.

**Review by cmagone — COMMENTED** [review]
LGTM

**Comment by mchan143** [comment]
@cmagone if all looks good, I can merge once you approve the proposed changes. Thanks!

**Review by cmagone — COMMENTED** [review]
LGTM

**Review by cmagone — APPROVED** [review]

**Pull request merged**
