### PR TITLE
Operations new UI control bar

### PR DESCRIPTION
**Pull request by iguannalin**
## Description

Reorganized the controls in the operations page for consistency with other pages

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by mshkolnik22** [comment]
Hi, @iguannalin - I sent an email with a couple of minor things like spacing and font.

**Review by mshkolnik22 — COMMENTED** [review]
Hi - @iguannalin, looks really good. I sent a link to a document with 2 small things like font and spacing.

**Comment by argaudreau** [comment]
Great work on this! As we talked about I removed the description and tweaked some of the margins and padding on some elements to make that control bar as small as possible. I made a PR for it, let me know if you think that'll work or not:

https://github.com/mitre/caldera/pull/2439

**Comment by iguannalin** [comment]
> Hi - @iguannalin, looks really good. I sent a link to a document with 2 small things like font and spacing.

Fixed!

**Comment by iguannalin** [comment]
> Great work on this! As we talked about I removed the description and tweaked some of the margins and padding on some elements to make that control bar as small as possible. I made a PR for it, let me know if you think that'll work or not:
> 
> #2439

Merged!

**Review by mshkolnik22 — APPROVED** [review]
@iguannalin - Checked on four browsers, logging in both as red and blue. Looks amazing.

**Review by argaudreau — APPROVED** [review]
Looks great to me!

**Pull request merged**
