### PR TITLE
Add rerun operation button

### PR DESCRIPTION
**Pull request by argaudreau**
## Description

When an operation finishes, the stop, pause, and other state controls are hidden and only a Re-run button is displayed. Clicking it will start a new operation with the exact settings used on the currently selected operation.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Operations that aren't finished behave as they did before, and when they are finished only the re-run button is displayed. Clicking the re-run button yielded no errors and the new operation is selected.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by iguannalin — COMMENTED** [review]
Looks good! Only thing I found was if I keep re-running the same operation, the name can get very long with the timestamp

Screen Shot 2022-03-08 at 11 44 00

**Comment by argaudreau** [comment]
Fixed that date issue -- regex will now overwrite the date if it exists.

**Review by iguannalin — APPROVED** [review]
lgtm!

**Review by cmagone — APPROVED** [review]
Very useful for testing! Keeping the same name and adding a timestamp will really help with organization and reporting after the fact.

**Pull request merged**
