### PR TITLE
WIP: virts-1021

### PR DESCRIPTION
**Pull request by ArtificialErmine**
Adds ability bucketing subsystem, as well as planner handles to access it.

### CODE REVIEW

**Comment by privateducky** [comment]
i'll let @khyberspache do the first pass here but my general feeling (off a brief code review) is that this is a really interesting idea -- but i'm not clear on how it will be worked in. i see two options:

1) embedded in our existing code (which is the current way you're approaching this). this is good if we think the bucket idea will be really integral to abilities and how we handle them - and if an ability objectively falls into a bucket.
2) as a wrapper, which we can apply separately and modify often. this would be good if we think the abilities may fall into different buckets based on context or anything subjective.

**Comment by privateducky** [comment]
per a convo with @khyberspache and @wbooth, we believe adversary packs already play the part of buckets, especially if we add the concept of "dynamic packs" created at run-time (like a tactic = a pack).

**Comment by khyberspache** [comment]
@ArtificialErmine Extending on what @privateducky said, I think what we can do is leverage existing packs assigned to an adversary and/or create dynamic packs at run-time (based on tactics and/or arbitrary pack definitions).  What are your thoughts?

**Comment by privateducky** [comment]
are we killing this PR or building on it, per our convo?

**Comment by khyberspache** [comment]
Let's leave open for now - tomorrow during our meeting Caleb and I will flesh out our approach.

**Comment by khyberspache** [comment]
Closing as we have our plan and are now executing said plan

**Pull request closed without merging**
