### PR TITLE
Added approve discard to view command modal, for manual operations

### PR DESCRIPTION
**Pull request by iguannalin**
## Description

(insert summary)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by mshkolnik22** [comment]
Just noticed that under Operations, I created a new one, and after adding a manual command, stopping it, and then deleting, it cannot add a new one again:
image

**Review by argaudreau — CHANGES_REQUESTED** [review]
I ran a manual op with an adversary selected, and after approving/discarding a link, it will flicker between its actual state and "pending" once a new link is waiting for a manual command.

https://user-images.githubusercontent.com/6034483/155155820-0b032442-8153-480c-90cb-cc2a8720364f.mp4

The link/ability names are named "Manual Command" after approving or denying, which overwrites the ability name from the adversary. If that's how it comes from the API that's fine, but wanted to see if we were accidentally overwriting it or something.

I was also thinking of a way to make it more apparent when a link is waiting for a user's input. Any objections to move the approve/discard buttons to the link row itself instead of the modal? That or adding an icon or message on the link to let them know to check out the command modal.

**Comment by iguannalin** [comment]
> I ran a manual op with an adversary selected, and after approving/discarding a link, it will flicker between its actual state and "pending" once a new link is waiting for a manual command.
> 
>  ManualCommandsFlicker.mp4 
> The link/ability names are named "Manual Command" after approving or denying, which overwrites the ability name from the adversary. If that's how it comes from the API that's fine, but wanted to see if we were accidentally overwriting it or something.
> 
> I was also thinking of a way to make it more apparent when a link is waiting for a user's input. Any objections to move the approve/discard buttons to the link row itself instead of the modal? That or adding an icon or message on the link to let them know to check out the command modal.

The command coming back from the API is named Manual command, so I'll leave that.

That's a really good idea, to let users know if the command needs to be approved/discarded manually. The view command column used to have all the edit controls in-row, but we decided to move it to a modal because it was cleaner than cramming it all into the column. I added a warning button and icon to let users know they can "Review Command" in a manual operation.

**Review by argaudreau — APPROVED** [review]
Looks great!

**Pull request merged**
