### PR TITLE
Add support for FreeBSD

### PR DESCRIPTION
**Pull request by alonsobsd**
## Description

This is a initial support for FreeBSD

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by alonsobsd** [comment]
image
image
image

Red Team captures

**Comment by alonsobsd** [comment]
image
image
image

Blue Team captures

**Comment by alonsobsd** [comment]
Take a look at the following links for other pull request necessaries for complete this integration 

https://github.com/mitre/atomic/pull/39
https://github.com/mitre/emu/pull/33
https://github.com/mitre/gameboard/pull/33
https://github.com/mitre/human/pull/36
https://github.com/mitre/manx/pull/40
https://github.com/mitre/response/pull/74
https://github.com/mitre/sandcat/pull/431
https://github.com/mitre/stockpile/pull/563
https://github.com/mitre/training/pull/168

**Comment by alonsobsd** [comment]
Hello, I have sent a pull request for include FreeBSD into atomic-red-team yaml used by Caldera atomic plugin. It will help us a better integration of FreeBSD with Caldera 

https://github.com/redcanaryco/atomic-red-team/pull/2413

**Comment by clenk** [comment]
Hi @alonsobsd, thank you for your contribution! Unfortunately, we don't currently have the resources to support another platform going forward.

**Comment by alonsobsd** [comment]
> Hi @alonsobsd, thank you for your contribution! Unfortunately, we don't currently have the resources to support another platform going forward.

Hi @clenk, I have added MITRE Caldera to FreeBSD ports tree (https://www.freshports.org/security/caldera), I mantain and test caldera on FreeBSD each new release. If you have not resource for maintained new platform I can contributed sending patch files for it if you want (I review and apply my patch files anyway to FreeBSD ports). Really it needs minor modifications because it is similar like Linux support. What do you think?

**Comment by clenk** [comment]
Hi @alonsobsd, the team has discussed this and is interested in enabling FreeBSD support. Would you mind reaching out to [caldera@mitre.org](caldera@mitre.org)? We would like to schedule a brief call to make sure we are all aligned in terms of expectations, if that works for you.

Thank you!

**Comment by alonsobsd** [comment]
Hi @clenk it is great :). I'll try contact to caldera@mitre.org as soon as possible. Thanks

**Comment by grahamperrin** [comment]
Refresh.

**Pull request closed without merging**
