### PR TITLE
Fix fact source creation and editting 

### PR DESCRIPTION
**Pull request by argaudreau**
## Description

There was unexpected behavior and bugs when creating facts, rules, and relationships on a fact source. This PR ensures that all three categories can be created, edited, and removed.

The fact source selection was also changed to a dropdown to match other core pages.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested in FF, Chrome, and Safari, all of which produced no console errors and behaved as exected:
* Create, duplicate, and remove fact source
* Create, edit, delete facts, rules, and relationships
* Modify the name of the source

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by mshkolnik22 — COMMENTED** [review]
@argaudreau  - I tested the changes as you asked and found a few issues. I'm sharing them by email with screenshots.

**Comment by argaudreau** [comment]
@mshkolnik22 I fixed all the errors/suggestions you made, feel free to take another look

**Review by iguannalin — APPROVED** [review]
lgtm!

**Review by mshkolnik22 — COMMENTED** [review]
@argaudreau In Chrome, logged in as a blue user, I created a Source named 'bob'. I added 1 fact. When I switch from 'bob' to Alice, and then try to switch back to 'bob', I cannot see my info and only Alice stays in that div. So the section does not refresh. Will email the screenshot.

**Comment by mshkolnik22** [comment]
I’m not on my computer, so I can’t really verify. So I’m approving to unblock.

**Review by mshkolnik22 — APPROVED** [review]

**Pull request merged**
