### PR TITLE
virts-1221

### PR DESCRIPTION
**Pull request by ArtificialErmine**
Implemented underlying basis for objectives and goals. System doesn't currently do anything (that'll be in subsequent MRs since we're breaking this up into chunks), but this is the groundwork

### CODE REVIEW

**Comment by privateducky** [comment]
main difference between this and the last swag? 1143 if I'm thinking correctly

**Comment by christophert** [comment]
@privateducky This is for objectives, 1143 looks to be for goals.

**Comment by ArtificialErmine** [comment]
@privateducky This is the underlying objects part of 1143, both objectives/goals. The rest of 1143 has been broken up across a collection of other tickets, so they'll be coming along.

**Comment by privateducky** [comment]
awesome PR. I literally have no comments for you!

**Pull request merged**
