### PR TITLE
UI support for Parsers and Requirements on Abilities

### PR DESCRIPTION
**Pull request by ArtificialErmine**
## Description

Working display/create system for requirements and parsers in the UI. Addresses the request of #2512.

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

This has been tested locally. 

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [NA] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by ArtificialErmine** [comment]
@argaudreau - Any thoughts you might have about this would be greatly appreciated. It's definitely a little on the rougher side.

**Review by christophert — CHANGES_REQUESTED** [review]
Changes seem to break Creating new Ability function since these fields are not filled out yet.

**Comment by ArtificialErmine** [comment]
> Changes seem to break Creating new Ability function since these fields are not filled out yet.

Thanks for catching this - I think I've found and addressed the root issue.

**Comment by argaudreau** [comment]
I put up a PR with some very minor changes to padding on the parser inputs: https://github.com/mitre/caldera/pull/2531

Other than that looks good to me!

**Review by argaudreau — APPROVED** [review]
lgtm!

**Review by christophert — COMMENTED** [review]
This fix for the ability view works now but there is some unrelated change in the framework that breaks the ability if I modify it and save. This PR is _probably_ good to go but more investigation needs to be put in as to why the framework doesn't properly save the ability.

**Review by clenk — APPROVED** [review]

**Comment by christophert** [comment]
Upon further inspection, the framework converts v0 abilities to v1 upon save. This doesn't affect any framework functionality - though there is a bug where the new ability format is not accepted when adding abilities to manual operations.

**Review by christophert — APPROVED** [review]

**Pull request merged**
