### PR TITLE
VIRTS-3370 Exfiltration Operations Subdirectory

### PR DESCRIPTION
**Pull request by yee-jonathan**
## Description

Caldera currently only goes one layer deep from the default directory when saving files. Each exfiltrated file is saved under the agent name. As such, if the same operation is run repeatedly, exfiltrated files with the same name will be overwritten.

This change creates an additional layer by adding a subdirectory using the operation's name and timestamp. The corresponding files are saved in a directory within the agent using a "YearMonthDay_HourMinuteSecond" format. This allows for the repeated running of an exfiltration adversary while preserving the exfiltrated files for each run. This change also provides visual feedback for which operation the file originated from. 

The html page was also updated to show the new tree structure.

Old structure:

- Exfiltration root folder (default: /tmp/caldera)
  - Agent Name Folder
    - Exfil File

New structure:

- Exfiltration Root Folder (default: /tmp/caldera)
  - Agent Name Folder
    - Operation Name/Time Folder
      - Exfil File

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Looked at Caldera logs to see if any additional bugs were generated when starting the server.

Used range to setup a single host-client environment. Ran a file exfiltration operation (i.e. Thief adversary) multiple times to test that exfiltrated file was preserved under the appropriate agent and folder.

Tested updated exfiltration page by navigating to and refreshing the page. Ensured that files were downloadable and correct by downloading and hashing said files.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by yee-jonathan** [comment]
Closed previous PR since code checks were not resolving. Reopened a new PR with a single commit since old branch had several commit that were no longer relevant since the requirements for fixing this bug had changed.

**Review by clenk — APPROVED** [review]
Looks good to me.

As noted on the previous PR, "Code Quality pipeline is only failing since this is from a fork which does not have our SonarCloud tokens. Tests and linting pass." - christophert

**Review by argaudreau — APPROVED** [review]
Template changes look good to me!

**Review by christophert — APPROVED** [review]
LGTM - testing & lining passes

**Pull request closed without merging**
