### PR TITLE
[VIRTS-2099] Fire event when link status changes

### PR DESCRIPTION
**Pull request by bworrell**
## Description
Related: #2112 

~Note that this is currently based off of the #2112 branch. I will change the base branch after it gets merged.~ Done.

Fire an event whenever the status of a link is changed.

Events are not fired when...
* The status is set for the first time via the initializer
* The status is set (e.g., `link.status = -3`) but the value is the same as its current value

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
* All tests pass
* Added unit tests to verify events are fired when expected
* Ran an operation successfully
* After operation I shut down the server and restarted it without `--fresh` to make sure pickle didn't have any issues.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by b17zr — APPROVED** [review]

**Review by clenk — DISMISSED** [review]
Not a big deal and it predates this PR anyway, but I find it interesting that an operation has `state` but a link has `status`. Wonder if they should be consistent down the road?

**Comment by bworrell** [comment]
> Not a big deal and it predates this PR anyway, but I find it interesting that an operation has `state` but a link has `status`. Wonder if they should be consistent down the road?

I had wondered if there was a reason for the different terms. If there isn't a distinction, then I think they should probably be the same.

**Comment by bworrell** [comment]
@clenk @b17zr re-requesting a review. I updated the base branch on this and pushed up one commit since a method on `BaseService` was made available to me.

**Comment by clenk** [comment]
> I had wondered if there was a reason for the different terms. If there isn't a distinction, then I think they should probably be the same.

I don't think there's a reason. Looking through git history I think the difference was just to preserve backwards compatibility through some major refactors way back.

**Review by clenk — APPROVED** [review]

**Pull request merged**
