### PR TITLE
Continue instruction until completed

### PR DESCRIPTION
**Pull request by supersquirel500**
## Description

Continue sending instruction from operation until it is reported as finished.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

After push to github created a separate directory, pulled the changed branches, ran server, ran operation, works correctly.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by unkempthenry** [comment]
@supersquirel500 , was there going to be a related PR going to gocat/sandcat?

**Comment by unkempthenry** [comment]
related https://github.com/mitre/gocat/pull/42/files

**Comment by unkempthenry** [comment]
@supersquirel500 , 

Check out this PR as an alternative to the changes in sandcat (keeps the `go` concurrency alive ) https://github.com/mitre/gocat/pull/46

**Comment by unkempthenry** [comment]
waiting on  https://github.com/mitre/gocat/pull/46

**Review by clenk — APPROVED** [review]

**Comment by wbooth** [comment]
@clenk how has this been tested?

**Comment by clenk** [comment]
@wbooth updated submodules to include mitre/gocat#46, ran operations successfully using sandcat, ragdoll, and manx.

**Comment by wbooth** [comment]
@clenk can you include a test that tests when the checkins occur multiple times between execution of a command -- we should ensure that we aren’t repeating an instruction when it hasn’t finished

**Review by wbooth — CHANGES_REQUESTED** [review]
testing issues need to be addressed before this can go in

**Pull request closed without merging**
