### PR TITLE
Remove history list of "select a profile" input

### PR DESCRIPTION
**Pull request by pierregi**
## Description

Change on the adversary page to correct a bug that show the list of previous search of adversary in front of the real list.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by argaudreau — APPROVED** [review]
Thanks for the contribution @pierregi! Good catch, I tested locally and can confirm that autocomplete no longer overlays the real list.

**Review by ZacharyLPalmer — APPROVED** [review]
Good catch! Thanks for contributing.

**Comment by argaudreau** [comment]
Hey @pierregi, could you make another PR with the same changes, but off of a branch from this repo instead of your fork? We aren't able to merge this because the checks aren't passing due to keys not being present on your fork. Add myself and @ZacharyLPalmer as reviewers and we'll get this merged in!

**Comment by pierregi** [comment]
> Hey @pierregi, could you make another PR with the same changes, but off of a branch from this repo instead of your fork? We aren't able to merge this because the checks aren't passing due to keys not being present on your fork. Add myself and @ZacharyLPalmer as reviewers and we'll get this merged in!

Sorry, but I am not allowed to create a branch

**Pull request closed without merging**
