### PR TITLE
added agent jitter sleep

### PR DESCRIPTION
**Pull request by khyberspache**
https://github.com/mitre/sandcat/pull/79
https://github.com/mitre/chain/pull/151

agents can now sleep between jitter intervals and go untrusted if they break max

### CODE REVIEW

**Comment by privateducky** [comment]
If we add this functionality, I think I'd rather the "work" happen on the server-side vs the agent. For example, I think this PR can occur without changing the Sandcat plugin at all. The sleep should be returned to the agent the same way it does now, but the value will vary based on the min/max (jitter). 

This would be similar to how we handle the jitter between running commands. If you look at the list of instructions we send to the agent, each instruction contains a command and a sleep interval (for how long to wait before running the next command). This "random" time is selected server-side when we create the link (planning_svc).

**Comment by khyberspache** [comment]
That's a really good idea.  I'll tweak and re-update.  This is useful for the Red Team use cases...

**Comment by khyberspache** [comment]
https://github.com/mitre/caldera/pull/503

**Comment by privateducky** [comment]
closing as duplicate

**Pull request closed without merging**
