### PR TITLE
Add option to rename facts

### PR DESCRIPTION
**Pull request by JamieScottC**
## Description

- This adds an input field to a fact source card which allows the ability to rename facts name/trait
- Also removes any weird behavior when deleting values from a fact. Previously values wouldn't be deleted or they would be, but it wouldn't be reflected on the UI.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Bug fix 

## How Has This Been Tested?

I have tried editing multiple fact names and then refreshed to make sure the changes are saved

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by JamieScottC** [comment]
Also just pushed another commit to hopefully fix any weird behavior when deleting values from a fact.

**Comment by morinjmit** [comment]
Is it possible to just make the name field thats already there editable when a user clicks on a fact? So like instead of adding another input below the fact name to change can you make the top one able to be edited? If not maybe hide the top one when the edit window is open just so the fact name isn't showing up twice which could be a little confusing or less straight forward to the user.

Other than that looks good to me

**Comment by JamieScottC** [comment]
> Is it possible to just make the name field thats already there editable when a user clicks on a fact? So like instead of adding another input below the fact name to change can you make the top one able to be edited? If not maybe hide the top one when the edit window is open just so the fact name isn't showing up twice which could be a little confusing or less straight forward to the user.
> 
> Other than that looks good to me

Good point! Just pushed that change

**Review by morinjmit — APPROVED** [review]
Looks good now!

**Review by clenk — APPROVED** [review]
LGTM

**Comment by JamieScottC** [comment]
I just committed another fix for a bug that @elegantmoose noticed. Hopefully one of the last🤞!

**Review by elegantmoose — APPROVED** [review]

**Pull request merged**
