### PR TITLE
Agent IP addresses

### PR DESCRIPTION
**Pull request by raviserota**
## Description

Modified sandcat agent to collect all non-loopback IPv4 addresses in use on its host. (https://github.com/mitre/gocat/pull/48)
Modified agent object to include a list of host IP addresses. Also added this variable to list of variables to update with heartbeat. Finally, changed the agent front-end to display the list of host IP addresses in the agent modal.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Checked agent modal for sandcat agent, host IP addresses were listed. For other agents, IP address list was empty.
Ran pytest, all tests passed.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by mchan143** [comment]
The changes here look good to me. 

@raviserota go ahead and check off the boxes in your PR description up top. You should add back in the checklist options regarding tests (you updated tests already so that's good to check off) and also documentation. I think a PR to fieldmanual adding the new attribute to the list of agent attributes in _How to Build Agents_ would be a good place to indicate this functionality for users who want their custom agents to report host IP addresses in the GUI.

**Review by mchan143 — COMMENTED** [review]
The changes here look good to me.

@raviserota go ahead and check off the boxes in your PR description up top. You should add back in the checklist options regarding tests (you updated tests already so that's good to check off) and also documentation. I think a PR to fieldmanual adding the new attribute to the list of agent attributes in How to Build Agents would be a good place to indicate this functionality for users who want their custom agents to report host IP addresses in the GUI.

**Comment by raviserota** [comment]
Sounds good. Thanks for the PR tips.

**Comment by unkempthenry** [comment]
@mchan143 if this looks good, can you you officially mark the review status as "approved" :) 

@raviserota , will this break anything if we merge it in before https://github.com/mitre/gocat/pull/48 ?  Is caldera still compatible with agents that don't report IP addresses?  (seems like it should be...)

**Review by mchan143 — APPROVED** [review]

**Review by unkempthenry — APPROVED** [review]
Nicely done 👍

**Comment by unkempthenry** [comment]
@wbooth , this PR allows agents to report their IP addresses to the caldera server automatically. 

Note: I noticed some unrelated issue with planners not loading with this branch and certain plugin commits (unsure the exact cause with my configuration), but everything worked great once I merged these changes with master's HEAD.

**Pull request merged**
